### ISSUE TITLE
Game quit while fighting a goblin.

### ISSUE THREAD

**Issue by sk8-knight** [wlpj2011/test-roguelike#5] opened 2021-07-17 17:15 UTC
Traceback (most recent call last):
  File "main.py", line 57, in <module>
    main()
  File "main.py", line 35, in main
    handler.on_render(console = root_console)
  File "/Users/Kate/Documents/GitHub/W-test-roguelike/input_handlers.py", line 252, in on_render
    string = f"b) Strength (+1 attack, from {self.engine.player.fighter.power})",
AttributeError: 'Fighter' object has no attribute 'power'
<img width="719" alt="Screen Shot 2021-07-17 at 1 15 15 PM" src="https://user-images.githubusercontent.com/56699319/126044756-582020ff-1eb7-473b-a9ac-db5431d6b262.png">

**Comment by wlpj2011** [comment] 2021-07-17 17:42
Bug caused by referencing variables that didn't exit any more upon gaining enough xp to level up. Fixed by making it reference the correct variables.

**Closed as completed by wlpj2011** 2021-07-17 17:42 UTC
Labels: bug
